export enum ActionType {
  GET_PRODUCT = "GET_PRODUCT",
  GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CART_RESET = "CART_RESET",
}
